export interface Topic {
  id:     string;
  korean: string;
  english: string;
  icon:   string;
  chips:  string[];
}

export interface Word {
  id:          string;
  korean:      string;   // headword
  english:     string;   // English gloss
  grade:       '초급' | '중급';   // krdict vocabulary level
  pos?:        string;   // part of speech
  definition?: string;   // Korean krdict definition
  example?:    string;   // krdict example sentence
}

// Grammar pattern generated by LLM (no fixed DB)
export interface GrammarPattern {
  id:      string;   // e.g. "g1", "g2"
  pattern: string;   // e.g. "-(으)니까"
  meaning: string;   // e.g. "because / since"
  example: string;   // Korean example sentence
  level?:  'beginner' | 'intermediate';
}

// One section in the speech timeline
export interface TimelineSection {
  id:    string;
  label: string;           // e.g. "Open", "The story"
  cue:   string;           // Speaking prompt in English
  words: {
    id:      string;
    korean:  string;
    english: string;
  }[];
  grammar: GrammarPattern | null;  // Grammar attached to this section (or null)
}

